### ISSUE TITLE
Feature Request: Facebook

### ISSUE THREAD

**Issue by Spitfire1900** [palant/searchlinkfix#15]
Add Search Link Fix capabilities to the website Facebook.

**Comment by palant** [comment]
Search Link Fix extension doesn't manipulate links - it relies on the links being "correct" originally, and merely prevents them from being changed after the fact. That doesn't seem to be the case for Facebook, the original link already goes though l.facebook.com so Search Link Fix would have to guess what the "real" link target is. This is out of scope for this extension, as are non-search pages in general (the latter because it would make explaining what this extension does unnecessarily complicated).

**Comment by Croydon** [comment]
@palant I see the exact opposite. The href attribute of links is original, but there is an onclick event which manipulates.

Facebook support would be indeed great.
