### ISSUE TITLE
Does not work on Google News

### ISSUE THREAD

**Issue by wbt** [palant/searchlinkfix#19]
The extension does not prevent onclick link rewriting on https://news.google.com/.  Can the extension (or if not the extension, the documentation) be updated to reflect that?  
Thanks much!

**Comment by palant** [comment]
I've added support for Google News, will upload a new release to AMO shortly.

**Comment by wbt** [comment]
Thanks!

**Comment by mnmelo** [comment]
I just tried this extension today on Firefox on the Mac (v63.0.3) and, although it works fine for google searches it does not prevent link mangling in google news.

Perhaps google has changed their news mangling process since the https://github.com/palant/searchlinkfix/commit/2ad46155f421eb47fdbdf5ef46259e3bef9e16e9 feature addition? It has certainly changed its layout since then.

**Comment by palant** [comment]
Yes, Google News was redesigned a few months ago. The new version serves up mangled links from the start, the original link is no longer there. This means that this extension cannot do anything about it, same is true for any other extension from the look of it - there simply doesn't see to be any way to get the original link without going through the redirect.

**Comment by palant** [comment]
You are right, there is some data structure containing the original URL. So it should be possible to recover, with massive potential for breaking site functionality. Since I don't have much time to invest into this extension, I'm not willing to take such risks.
