### ISSUE TITLE
PaleMoon support

### ISSUE THREAD

**Issue by nelegalno** [palant/searchlinkfix#26]
Please add [PaleMoon] (https://www.palemoon.org/info.shtml) support to the latest version of the addon.

http://dev.addons.palemoon.org/jetpack/

**Comment by palant** [comment]
PaleMoon's SDK support is very outdated, it doesn't support JPM-built extensions (these require Firefox 38 and higher). In particular, neither `resource://gre/modules/commonjs/toolkit/require.js` nor `resource://gre/modules/commonjs/sdk/addon/bootstrap.js` exist - so the extension won't even start up.

**Comment by nelegalno** [comment]
Considering v1.4.9 works fine I don't see why can't you support it in v1.5.x or backport the fixes from it to the v1.4 branch?

**Comment by palant** [comment]
1.4.9 wasn't based on the Add-on SDK. I switched back to the Add-on SDK because with JPM it finally got mature enough, also because it will stay supported in Firefox. I'm not going back, you are free to continue using 1.4.9 however - outdated add-on for an outdated browser, that's how it usually works.

**Comment by nelegalno** [comment]
You'd better check you're facts first, or are you calling a product that was last updated on 28 Nov 2015 and it's next version update is planed for - outdated browser? Just because it's authors decided to not follow in the same direction Mozilla is taking Firefox it's not making it outdated.

**Comment by palant** [comment]
I know the facts, and it doesn't matter when the last release was. It's based on Gecko 24 (regardless of how they call it), and while they try to backport selected changes the technological base of the browser is more than two years old (yes, that's a lot). That shows when you look at the Add-on SDK, it shows in many other places as well. Even if I decided to drop the Add-on SDK and instead support E10S by other means - I'm fairly certain that this wouldn't make you happy because the E10S code in Palemoon is similarly outdated. Supporting Gecko 46 and Gecko 24 in the same build just doesn't work.

**Comment by nelegalno** [comment]
As far as I'm aware E10S is NOT supported in PaleMoon, and I'm asking for Goanna support and not Gecko ...

**Comment by palant** [comment]
E10S code landed as far back as Gecko 4 and extensions supporting E10S (which will soon mean all Firefox extensions) use it regardless of whether E10S is actually enabled in the browser or not - that's the only way backwards compatibility can work here.
