### ISSUE TITLE
Performance impact on Youtube

### ISSUE THREAD

**Issue by anewuser** [palant/searchlinkfix#31]
Is this extension optimized to run only on the search engine, or can it affect the performance of other pages that makes requests to google.com domains? When I open Youtube, `about:performance` informs that **Google search link fix** may be slowing down Firefox 48.

**Comment by palant** [comment]
Is that something you can reproduce reliably or a one-time thing?

In general, the info displayed on `about:performance` should be taken with a grain of salt. For me it shows "YouTube may currently be slowing down Firefox" and "about:performance may currently be slowing down Firefox" - note how it says "may" there, there results aren't entirely reliable and misattributions aren't too uncommon from what I've seen.

Google search link fix is shown as performing fine which is expected. While this extension isn't limited to google.com (simply because Google Search isn't limited to google.com and recognizing Google Search by domain name is actually far from trivial), the operation it performs everywhere else is so trivial that performance side-effect would be highly unexpected.

**Comment by anewuser** [comment]
I know that `about:performance` isn't extremely reliable, but it only change the status for an extension when it actually does something. It may be trivial on a modern decent computer, but when used in combination of other extensions that also have some impact on slower laptops, it becomes a problem.

>recognizing Google Search by domain name is actually far from trivial),

I thought that you could specify what domains your extension should run on with a regex, like user scripts do.

**Comment by palant** [comment]
> I thought that you could specify what domains your extension should run on with a regex, like user scripts do.

I'd rather not assume that anything with "google" in it is Google Search :-)

**Comment by anewuser** [comment]
But the onclick event could still test only pages with "google" instead of all pages in general?

**Comment by palant** [comment]
In order to impact performance as little as possible, the website test is only performed once you click. For Yandex or Google Groups for example this goes by host name, for Google Search or Google News the host name isn't a reliable indicator - these are recognized by other means.
