### ISSUE TITLE
Does not work is Javascript disabled

### ISSUE THREAD

**Issue by ko-dever** [palant/searchlinkfix#69]
Hi.

First, thanks for your extension 👍 .

Sometimes I like to disable everything I can (thanks [uBlock Origin](https://github.com/gorhill/uBlock)) to just have simple and quick results.
However in this case I noticed that it does not work anymore when Javascript is disabled.

As you can see on this screenshot, the link is still tracked by Google.
![cc](https://user-images.githubusercontent.com/4114656/46261634-0af2b300-c4e6-11e8-9253-b5a4313738e5.png)

Even if I copy the link, your extension does not modify it.

Do you think something is possible to fix this ?

Thanks 🙂  .

**Comment by palant** [comment]
From "Known limitations":

* This extension cannot recover links after they have been modified. This means that it doesn’t work on Google Search on smartphones (tablet version will work fine) or if JavaScript is disabled — Google will produce modified links from the start rather than changing them when you click the link.
