### ISSUE TITLE
Links are not fixed without javascript

### ISSUE THREAD

**Issue by NilsHoyer** [palant/searchlinkfix#91]
I'm using the [NoScript](https://addons.mozilla.org/en-US/firefox/addon/noscript/) Add-on of Firefox and disabled all scripts for www.google.com.

Unfortunately, Google search link fix does not longer work after this.

Would be nice, if you would find a way to implement this.

**Comment by palant** [comment]
Yes, and that's in fact listed under "Known limitations":

* This extension cannot recover links after they have been modified. This means that it doesn’t work on Google Search on smartphones (tablet version will work fine) or if JavaScript is disabled — Google will produce modified links from the start rather than changing them when you click the link.
