### ISSUE TITLE
Not working anymore due to last Google (.com) updates on research results

### ISSUE THREAD

**Issue by francescor** [palant/searchlinkfix#96]
Firefox: 77.0.1 (64-bit)

As you well know Google (google.com) has lately changed the way it present links in results, in a seriously bad way: but if I disable javascript on google.com (with u-block origin) I still see the old version of how google rewrite url, but even with this the rewrite does not work.

Es.

https://www.google.com./url?q=https://artsandculture.google.com/partner/the-british-museum&sa=U&ved=2ahUKEwjSlOrNs4rqAhVF_q55HXE1444QFjAnegQIAhAB&usg=A44Vaw3JBuP0oZbV-2227n1Xe_TH

instead of 

https://artsandculture.google.com/partner/the-british-museum

**Comment by palant** [comment]
I'm not really sure what the issue is that you are reporting. It appears that you are on `www.google.com.` rather than `www.google.com` (note the trailing dot) - the extension doesn't apply to this domain, and also quite a bit of website functionality is broken then. How did you even get there?

As to disabling JavaScript, this extension won't work then (listed under "Known limitations"). Google produces a different search page then, where links are mangled from the start. This extension doesn't rewrite links, it merely prevents them from being mangled, so there is nothing it can do in this situation.

**Comment by francescor** [comment]
omg, you are more then right! 
sorry for wasting your time Wladimir.

That trailing dot: it's me, I am rewriting that domain automatically taking advantage of that https://www.reddit.com/r/webdev/comments/gzr3cq/fyi_you_can_bypass_youtube_ads_by_adding_a_dot/

thanks for the explanation, your extension rock!
